### PR TITLE
change all error values in store to be Error objects (fix #15)

### LINKED ISSUE #15: Error: `model.get(...).toJS is not a function` if API client puts `Error` value in rejected promises
This problem occurs when selecting a single record, using either `selectRecord` or `select`, if the library user's API client implementation puts `Error` values in rejected promises. Using `Error` values for rejections is a common practice, and is arguably a best practice.

The problem arises because the redux-crud-store reducers attempt to convert error values to Immutable data structures:

``` js
    // reducers.js, line 71
    case FETCH_ONE_ERROR:
      return state.setIn([id.toString(), 'fetchTime'], action.meta.fetchTime)
                  .setIn([id.toString(), 'error'], fromJS(action.payload))  // <-- conversion happens here
                  .setIn([id.toString(), 'record'], null)
```

Selector functions attempt to convert back to a plain Javascript object:

``` js
  // selectors.js, line 129
  if (model.get('error') !== null) {
    return {
      isLoading: false,
      needsFetch: false,
      error: model.get('error').toJS()
    }
  }
```

Immutable's `fromJS` function does not attempt to create immutable versions of `Error` values - it just returns the original value. So the later `.toJS()` invocation fails.

This relates to #9.

### PR DESCRIPTION
**Pull request by devvmh**
It works out well because you can still use error.message. I think this is really just a patch release, but I think this will be 4.1.0 just because it's a significantish change.

### CODE REVIEW

**Comment by devvmh** [comment]
build & tests pass for d52cdc9fcb499e47084b73b0ca86824d3d9c914f

File: src/selectors.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export type Selection<T> = {
   data?: T,
   isLoading: boolean,
   needsFetch: boolean,
-  error?: Error | { message: string },
+  error?: Error,
```
Comment (devvmh) [inline src/selectors.js:21]: This is the biggest change. I wonder if there should be even more severe checks to enforce this.

**Comment by devvmh** [comment]
@hallettj Could you look through the code to see if there are more spots that should be changed that you notice (any time you get a chance)?
